#!/bin/sh

cat > /Library/LaunchAgents/com.github.kiron1.proxydetox.plit <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>com.github.kiron1.proxydetox</string>
    <key>RunAtLoad</key>
    <true/>
    <key>ProgramArguments</key>
    <array>
      <string>/bin/sh</string>
      <string>-c</string>
      <string>exec "/usr/local/bin/proxydetox" "\$HOME/.config/proxydetox/proxy.pac" 3128</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
      <key>RUST_LOG</key>
      <string>info</string>
    </dict>
    <key>StandardOutPath</key>
    <string>/tmp/proxydetox.stdout</string>
    <key>StandardErrorPath</key>
    <string>/tmp/proxydetox.stderr</string>
  </dict>
</plist>
EOF
