#!/bin/sh

set -u

oldlabel=com.github.kiron1.proxydetox
oldagentplist=/Library/LaunchAgents/${oldlabel}.plist

label=cc.colorto.proxydetox
agentplist=/Library/LaunchAgents/${label}.plist

# Usage: uid label plist_file
kill_and_bootout() {
  if [ -e "${3}" ]; then
    /bin/launchctl kill TERM "gui/${1}/${2}"
    /bin/launchctl bootout "gui/${1}" "${3}"
  fi
}


if [ -e /dev/console ]; then
  uid=$(/usr/bin/stat -f %u /dev/console)
  # Cleanup potential old left-overs
  kill_and_bootout "${uid}" "${oldlabel}" "${oldagentplist}"
  rm -f "${oldagentplist}"

  kill_and_bootout "${uid}" "${label}" "${agentplist}"
fi

# Cleanup potential old left-overs
if /usr/sbin/pkgutil --packages | grep -q "${oldlabel}"; then
  /bin/rm -f "/usr/local/bin/proxydetox"
  /usr/sbin/pkgutil --forget "${oldlabel}"
fi
