[workspace]
members = ["duktape-sys", "duktape", "paclib", "paceval"]

[package]
name = "proxydetox"
version = "0.3.3"
edition = "2018"
homepage = "https://github.com/kiron1/proxydetox"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dependencies]
argh = "0.1"
base64 = "0.12"
dirs = "3.0"
env_logger = "0.7"
futures-util = { version = "0.3", default-features = false }
http = "0.2"
hyper = "0.13"
netrc = { git = "https://github.com/kiron1/netrc-rs", branch = "modernize" }
paclib = { path = "paclib" }
tokio = { version = "0.2", features = ["full"] }
tracing = "0.1"
tracing-attributes = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
