[workspace]
members = ["cproxydetox", "dnsdetox", "proxydetox", "paceval"]

# https://github.com/google/cargo-raze#cargo-workspace-projects
[workspace.metadata.raze]
# Usage:
#   cargo install cargo-raze
#   cargo raze

# The path at which to write output files.
#
# `cargo raze` will generate Bazel-compatible BUILD files into this path.
# This can either be a relative path (e.g. "foo/bar"), relative to this
# Cargo.toml file; or relative to the Bazel workspace root (e.g. "//foo/bar").
workspace_path = "//cargo"

# Location of aliases for dependencies to be rendered in the BUILD
# file located in cargo.
package_aliases_dir = "cargo"

# The set of targets to generate BUILD rules for.
targets = [
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
]

# The two acceptable options are "Remote" and "Vendored" which
# is used to indicate whether the user is using a non-vendored or
# vendored set of dependencies.
genmode = "Remote"

# Setting default_gen_buildrs to true will cause cargo-raze to generate
# build scripts for all crates that require them.
# This setting is a trade-off between convenience and correctness.
default_gen_buildrs = true

