[workspace]
members = [
    "cproxydetox",
    "detox_net",
    "dnsdetox",
    "duktape",
    "duktape-sys",
    "paceval",
    "paclib",
    "proxy_client",
    "proxydetox",
    "proxydetoxlib",
]
