[package]
name = "libsspi"
version = "0.1.0"
authors = ["kiron1 <kiron1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = "0.18"

[build-dependencies]
windows = "0.18"