#!/bin/sh

set -u

oldlabel=com.github.kiron1.proxydetox
agentplist=/Library/LaunchAgents/${oldlabel}.plist

# From https://www.apple.com/uk/business/docs/site/Kerberos_Single_Sign_on_Extension_User_Guide.pdf
if [ -e "${agentplist}" ]; then
  loggedInUser=$(echo "show State: /Users/ConsoleUser" | scutil | awk '/Name : / && ! / loginwindow/ { print $3 }')
  loggedInUID=$(id -u "${loggedInUser}")
  launchctl kill TERM "gui/${loggedInUID}/${oldlabel}"
  launchctl bootout "gui/${loggedInUID}" "${agentplist}"
  rm -f "${agentplist}"
fi

if pkgutil --packages | grep -q "${oldlabel}"; then
  rm -f "/usr/local/bin/proxydetox"
  pkgutil --forget "${oldlabel}"
fi
