[package]
name = "cproxydetox"
version = "0.1.0"
edition = "2018"
homepage = "https://github.com/kiron1/proxydetox"

[lib]
crate-type = ["staticlib"]

[dependencies]
dirs = "3.0"
libc = "0.2"
proxydetox = { path = "../proxydetox" }
tokio = { version = "1.0", features = ["rt-multi-thread"] }
