#!/bin/sh
#
# Publish the mdbook output to the gh-pages branch to make it viewable online.
#
# Working directory must be root of checkout.
#
# Usage:
#
#     ./tools/publish-gh-pages
#

set -eu

GIT_WORK_TREE=$(mktemp -d /tmp/gh_pages.XXXXXX)
trap 'rm -rf -- "${GIT_WORK_TREE}"' EXIT INT

REMOTE=$(git config --get remote.origin.url)
git clone --single-branch --branch gh-pages "${REMOTE}" "${GIT_WORK_TREE}"
rm -rf -- "${GIT_WORK_TREE:?}/*"

make "PUBLICDIR=${GIT_WORK_TREE}" pages

git -C "${GIT_WORK_TREE}" config user.email "action@github.com"
git -C "${GIT_WORK_TREE}" config user.name "GitHub Action"
git -C "${GIT_WORK_TREE}" add --all
git -C "${GIT_WORK_TREE}" commit --amend --message "Publish GitHub Pages"
git -C "${GIT_WORK_TREE}" push --force origin HEAD
