#!/usr/bin/env bash

set -eu
set -o pipefail

prefix="version="

while getopts "r" o; do
  case "${o}" in
  r)
    prefix=""
    ;;
  *)
    echo "fatal error: invalid arguments"
    exit 1
    ;;
  esac
done
shift $((OPTIND - 1))

query=$(printf '"\($prefix)\(.packages[] | {name, version} | select(.name == "%s") | .version)"' "${1:-proxydetox}")
cargo metadata --format-version 1 --no-deps --offline --quiet | jq --arg prefix "${prefix}" -r "${query}"
