name: bump_version

on:
  workflow_dispatch:
    inputs:
      release_kind:
        description: 'Kind of version bump'
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
        required: true

jobs:
  bump:
    name: bump version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Install cargo-edit
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-edit

      - name: Bump version of proxydetox
        run: |
          cargo set-version --bump "${KIND}"
        env:
          KIND: ${{ github.event.inputs.release_kind }}

      - name: Cargo update
        run: |
          cargo update

      - name: Get new version
        id: new_version
        run: |
          ./tools/version | tee -a "${GITHUB_OUTPUT}"

      - name: Create PR
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Version ${VERSION}"
          git tag "v${VERSION}"
          git push
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.new_version.outputs.version }}
